### ISSUE TITLE
libstc++.tdb should be libstdc++.tdb?

### ISSUE THREAD

**Issue by sbryfcz** [RobertBiehl/caffe2-ios#3]
# Report

## What did you do?

I tried to update my build phases with: libstc++.tdb

## What did you expect to happen?

I expected to find that item in the prompt to add a build phase.

## What happened instead?

I could not find that item. I think you meant libstdc++.tdb
Maybe update the README?

**Comment by RobertBiehl** [comment]
@sbryfcz you are right, I'll update the README! Thanks!

**Comment by HenryHins** [comment]
I think you mean "libstdc++.tbd" notice its TBD not TDB. Took me half an hour to notice that :/
