### ISSUE TITLE
Error: Linker command failed with exit code1

### ISSUE THREAD

**Issue by suxiaoxinxin** [RobertBiehl/caffe2-ios#7]
When build the project always has a issue: Linker command failed with exit code 1. I really do not know how to figure out it. Thanks a lot!!!

**Comment by RobertBiehl** [comment]
@suxiaoxinxin Hi, can you please post the whole build log?

**Comment by suxiaoxinxin** [comment]
![Uploading 屏幕快照 2017-05-07 下午9.28.59.png…]()
I'm really a beginner.....

**Comment by suxiaoxinxin** [comment]
<img width="875" alt="2017-05-07 9 28 59" src="https://cloud.githubusercontent.com/assets/28506781/25781624/966e8d4c-336e-11e7-9071-3c25be118666.png">
Do you mean this?

**Comment by RobertBiehl** [comment]
Can you check if you did the "Additional steps:" in README.md
Unfortunately I did not yet get the pod configured correctly to not need additional configuration

**Comment by suxiaoxinxin** [comment]
I remove '-framework' from other linker flags, the error is gone but turn up some warning:
<img width="1141" alt="19408e66cf7b34ae2370332e9809bc4e" src="https://cloud.githubusercontent.com/assets/28506781/25803791/2e56cefa-342b-11e7-9a93-99692f5aaeaf.png">
 
<img width="1398" alt="47d722c1c355a82bd0a4ea291bc4e587" src="https://cloud.githubusercontent.com/assets/28506781/25803801/3c807c06-342b-11e7-8d91-54527d13c0fa.png">
Output of iphone6 like this:
![cea85e8333ba554a2d94aaeb7b3503a4](https://cloud.githubusercontent.com/assets/28506781/25803820/5881ec3c-342b-11e7-97dd-705a58b92421.png)
Did I make something wrong? Thanks!

**Comment by suxiaoxinxin** [comment]
I remove '-framework' from other linker flags, the error is gone but turn up some warnings:
<img width="1141" alt="19408e66cf7b34ae2370332e9809bc4" src="https://cloud.githubusercontent.com/assets/28506781/25803986/2cf31068-342c-11e7-9e34-6acd8f66ff55.png">

<img width="1398" alt="47d722c1c355a82bd0a4ea291bc4e58" src="https://cloud.githubusercontent.com/assets/28506781/25804027/55504b66-342c-11e7-8110-8b5344ab7859.png">

Output of iphone6 like this:

![cea85e8333ba554a2d94aaeb7b3503a](https://cloud.githubusercontent.com/assets/28506781/25804068/80f33e18-342c-11e7-8fe8-c3a47205766f.png)

Did I make something wrong?

**Comment by RobertBiehl** [comment]
Hi, it looks like you need to replace `let caffe =` with `self.caffe = `.
You assign to a local variable, and not the instance property.

Rob

**Comment by suxiaoxinxin** [comment]
Wow! It worked! Thank you! You're so cool!

**Comment by raininglixinyu** [comment]
@suxiaoxinxin Hi, how is the performance on your iphone6? My iphone6 costs 30ms to do a single predict step which is far from @RobertBiehl 's 6ms.

**Comment by RobertBiehl** [comment]
@raininglixinyu Make sure you benchmark the correct part. Currently the pod ensures BGR color layout. This could cost some performance. I better remove the benchmark metrics from the README ;)

I think this pod should be easy to use first, then worry about performance. We're still a bit off the first goal.
